# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contatos.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'contatos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontatos.proto\x12\x0b\x61genda_grpc\"C\n\x08Telefone\x12\x0e\n\x06numero\x18\x01 \x01(\t\x12\'\n\x04tipo\x18\x02 \x01(\x0e\x32\x19.agenda_grpc.TipoTelefone\"\x8e\x01\n\x07\x43ontato\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12(\n\ttelefones\x18\x04 \x03(\x0b\x32\x15.agenda_grpc.Telefone\x12\x30\n\tcategoria\x18\x05 \x01(\x0e\x32\x1d.agenda_grpc.CategoriaContato\"7\n\rListaContatos\x12&\n\x08\x63ontatos\x18\x01 \x03(\x0b\x32\x14.agenda_grpc.Contato\"3\n\x0eStatusResposta\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"%\n\x17\x43onsultarContatoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"W\n\x15ListarContatosRequest\x12\x30\n\tcategoria\x18\x01 \x01(\x0e\x32\x1d.agenda_grpc.CategoriaContato\x12\x0c\n\x04nome\x18\x02 \x01(\t*_\n\x0cTipoTelefone\x12\x1c\n\x18TIPO_TELEFONE_INDEFINIDO\x10\x00\x12\x0e\n\nTIPO_MOVEL\x10\x01\x12\r\n\tTIPO_FIXO\x10\x02\x12\x12\n\x0eTIPO_COMERCIAL\x10\x03*\x8f\x01\n\x10\x43\x61tegoriaContato\x12 \n\x1c\x43\x41TEGORIA_CONTATO_INDEFINIDO\x10\x00\x12\x13\n\x0f\x43\x41TEGORIA_AMIGO\x10\x01\x12\x15\n\x11\x43\x41TEGORIA_FAMILIA\x10\x02\x12\x17\n\x13\x43\x41TEGORIA_COMERCIAL\x10\x03\x12\x14\n\x10\x43\x41TEGORIA_OUTROS\x10\x04\x32\xfe\x01\n\rAgendaService\x12G\n\x10\x41\x64icionarContato\x12\x14.agenda_grpc.Contato\x1a\x1b.agenda_grpc.StatusResposta\"\x00\x12P\n\x10\x43onsultarContato\x12$.agenda_grpc.ConsultarContatoRequest\x1a\x14.agenda_grpc.Contato\"\x00\x12R\n\x0eListarContatos\x12\".agenda_grpc.ListarContatosRequest\x1a\x1a.agenda_grpc.ListaContatos\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contatos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOTELEFONE']._serialized_start=483
  _globals['_TIPOTELEFONE']._serialized_end=578
  _globals['_CATEGORIACONTATO']._serialized_start=581
  _globals['_CATEGORIACONTATO']._serialized_end=724
  _globals['_TELEFONE']._serialized_start=31
  _globals['_TELEFONE']._serialized_end=98
  _globals['_CONTATO']._serialized_start=101
  _globals['_CONTATO']._serialized_end=243
  _globals['_LISTACONTATOS']._serialized_start=245
  _globals['_LISTACONTATOS']._serialized_end=300
  _globals['_STATUSRESPOSTA']._serialized_start=302
  _globals['_STATUSRESPOSTA']._serialized_end=353
  _globals['_CONSULTARCONTATOREQUEST']._serialized_start=355
  _globals['_CONSULTARCONTATOREQUEST']._serialized_end=392
  _globals['_LISTARCONTATOSREQUEST']._serialized_start=394
  _globals['_LISTARCONTATOSREQUEST']._serialized_end=481
  _globals['_AGENDASERVICE']._serialized_start=727
  _globals['_AGENDASERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
